### ISSUE TITLE
None highlighted incorrectly after from keyword in Python code

### ISSUE THREAD

**Issue by rdbende** [rdbende/chlorophyll#13]
@Moosems:

> Paste the following:
> 
> ```py
> from
> None
> ```
> 
> None is highlighted as though it is an import

@rdbende:

> When pasting this Pygments yields Token.Name.Builtin.Pseudo for None, even though it's Token.Keyword.Constant. Probably a bug there.

@Moosems:

> Do you want to open an issue on pygments?

**Comment by rdbende** [comment]
Pygments thinks it's part of a `raise Exception from None` statement. It doesn't do it with other constants, like `True`.

**Comment by Moosems** [comment]
Bug to report to `Pygments` then?

**Comment by rdbende** [comment]
Not yet.

**Comment by rdbende** [comment]
> Pygments thinks it's part of a raise Exception from None statement. It doesn't do it with other constants, like True.

And I was right. Pull request opened: pygments/pygments#2406

**Comment by Moosems** [comment]
@rdbende Thanks! Now we just have to wait for a new release.
