### ISSUE TITLE
Lambda crash

### ISSUE THREAD

**Issue by Moosems** [rdbende/chlorophyll#14]
```python
from chlorophyll import CodeView


from tkinter import Tk
root = Tk()
text = CodeView(root)
text.pack()
def test():
    text.insert("end", "\n"*2)
    root.destroy()
    # Using after_idle still causes an error
    # The error caused by after_idle is exclusive to Mac OS
    # Error: objc[number]: Invalid or prematurely-freed autorelease pool hex_value.
    # root.after_idle(root.destroy)

root.after(10, test)
# root.after_idle(test)
# Using after_idle still causes an error when used with test()
# It causes a corrupted memory error
"""
invalid command name "4532481984<lambda>"
    while executing
"4532481984<lambda>"
    ("after" script)
objc[27242]: autorelease pool page 0x7fe67c93d000 corrupted
  magic     0x00000000 0x00000000 0x00000000 0x00000000
  should be 0xa1a1a1a1 0x4f545541 0x454c4552 0x21455341
  pthread   0x1170bd5c0
  should be 0x1170bd5c0
"""
root.mainloop()


root = Tk()
root.after(10, root.destroy)
root.mainloop()
```

**Comment by rdbende** [comment]
Where does that lambda come from?

Are you able to reproduce the issue with a plain `Text` widget?

**Comment by Moosems** [comment]
It doesn't happen with a plain `Text` widget and it comes from the `after()`

**Comment by Moosems** [comment]
I believe the issue is in `_cmd_proxy()` with the `after_idle()` fighting with the destroy (lambda issues are caused by after being cut short and then not being able to run):

```python
    def _cmd_proxy(self, command: str, *args) -> Any:
        ...
        if command == "insert":
            length = len(args[1].lstrip().splitlines())
            if length == 1:
                self._highlight()
            else:
                self.after_idle(lambda: self._highlight_lines(length))
            self.event_generate("<<ContentChanged>>")
        elif command in {"replace", "delete"}:
            self._highlight()
            self.event_generate("<<ContentChanged>>")
```

**Comment by Moosems** [comment]
Tested what happened when I removed this code and it worked just fine. I will have to find a workaround so the `after()`'s aren't competing.

**Comment by Moosems** [comment]
It's caused by the `after_idle()` wanting to run in the `cmd_proxy()` but when the time comes to run the app has already been closed meaning it can't and it is because of this `after_idle()` that no matter how long it waits to destroy the root that it still crashes.

**Comment by Moosems** [comment]
I could check in the after idle if the root still exists and run only if it . @rdbende your thoughts?

**Comment by rdbende** [comment]
Idk, what `root.winfo_exists()` does when the root has been destroyed, but could catch it in a `try` block.

**Comment by Moosems** [comment]
I'll give both a look when I'm near my laptop. I doubt the try block will work though because tcl issues normally still print in try blocks when I use them but I hope it works.

**Comment by Moosems** [comment]
Somewhere the after_idle got destroyed but this still breaks it:

```python
from chlorophyll import CodeView


from tkinter import Tk
root = Tk()
text = CodeView(root)
text.pack()
def test():
    text.insert("end", "\n"*2)
    root.after_idle(root.destroy)
    # The error caused by after_idle is exclusive to Mac OS
    # Error: objc[number]: Invalid or prematurely-freed autorelease pool hex_value.
    # root.after_idle(root.destroy)

root.after(10, test)
# root.after_idle(test)
# Using after_idle still causes an error when used with test()
# It causes a corrupted memory error
"""
objc[11327]: Invalid or prematurely-freed autorelease pool 0x7fb47a0250b8.
"""
root.mainloop()
```

`print(self.winfo_viewable())` and `print(self.winfo_exists())` both return true at the end so it definitely needs more looking into.

**Comment by Moosems** [comment]
Honestly, I don't care enough to work on this since I found a workaround in DIP and will close it for now until someone else needs it to work.
