### ISSUE TITLE
`_copy()` uses `tkinter`'s builtin copy function

### ISSUE THREAD

**Issue by Moosems** [rdbende/chlorophyll#17]
This is an issue because the clipboard in tkinter is deleted and emptied when the program is closed and this has been an issue for me in the past. I recommend we use `pyperclip`'s copy function as it is battle proven to work and not very memory intensive.

**Comment by rdbende** [comment]
So it does that on macOS as well?

**Comment by Moosems** [comment]
Yes, it most definitely does. I have lost countless hours of work to this in the past.

**Comment by rdbende** [comment]
The other day I wrote this comment on a tkinter PR: https://github.com/python/cpython/pull/26163#issuecomment-1500184564

**Comment by Moosems** [comment]
I would update it then :)
