### ISSUE TITLE
Highlighting issues.... still

### ISSUE THREAD

**Issue by Moosems** [rdbende/chlorophyll#29]
The following doesn't highlight properly:

```python
from chlorophyll import CodeView
from pygments import lexers
from tkinter import Tk

root = Tk()
cd = CodeView(root, lexer=lexers.PythonLexer)
cd.pack()
cd.insert("insert", "from\nfrom\nfrom")
root.mainloop()
```

**Comment by Moosems** [comment]
Fix this and #10.

**Comment by rdbende** [comment]
Actually, that would be the right way to highlight it. Just look at it in Porcupine.

**Comment by rdbende** [comment]
Probably because it's invalid syntax

**Comment by Moosems** [comment]
Well then, I guess it's a stupid issue lol.

**Comment by rdbende** [comment]
Where did you even get the idea to write 3 `from`s under each other? lol

**Comment by Moosems** [comment]
Lol I literally sometimes just mess around with the highlighting and type up random stuff to see what happens. This stuff came up when testing my additions if the indent dedent code and if it ever got accidentally triggered.
