### ISSUE TITLE
Add builtin linenumbers

### ISSUE THREAD

**Issue by rdbende** [rdbende/chlorophyll#4]
@Moosems:

> Find and replace, linenumbers, and a minimap could be based off of Porcupine by Akuli on GitHub. If this is meant to be an all builtin code editor than this would be a sensible addition

@rdbende:

> I plan to make linenumbers feature, but I think that the find and replace and the minimap are outside the scope of this project, and if someone needs such features, they would rather use they own than the builtin one 😏. This widget isn't meant to be an all builtin code editor, just a simple `CodeView` widget

@Moosems:

> Understood :)

> @rdbende I made a pretty good linebar in DIP if you want to steal it

> @rdbende I released a good linebar widget on [pypi](https://pypi.org/project/tklinenums/) :)

> Would we like to add the linebar widget?

**Comment by Moosems** [comment]
When I try adding Tklinenums it has some rendering issues and refuses to draw.

**Comment by rdbende** [comment]
Can you open a PR with it?

**Comment by Moosems** [comment]
I'm going to cross reference with DIP_dev and try to get reverting b in place while we try to figure out why it won't render the numbers.

**Comment by Moosems** [comment]
Fixed by #15
