### ISSUE TITLE
Embedding windows in Jupytor notebook instead of floating and access text

### ISSUE THREAD

**Issue by Nado15** [rdbende/chlorophyll#47]
Hi,

I really like this widget, thanks for that!

Is it possible to embed the window in Jupytor Notebook instead of letting it float? I want it to behave like a cell. And how can I access the typed text in order to process it?

**Comment by rdbende** [comment]
Hi!

You can access the typed text with the `w.get("1.0", "end")`

I don't know whether this widget can be embedded into a Jupyter notebook, as it is based on Tkinter, and I'm not sure Jupyter can show Tkinter widgets.

**Comment by Nado15** [comment]
Thanks I managed with your help and [this](https://stackoverflow.com/questions/14824163/how-to-get-the-input-from-the-tkinter-text-widget) to print out the text.

Here is the example code:

**Comment by Nado15** [comment]
Thanks a lot!

I managed to print out the text with your help and from [here](https://stackoverflow.com/questions/14824163/how-to-get-the-input-from-the-tkinter-text-widget)

Here is an example:

```python
from tkinter import Tk, Button

import pygments.lexers
from chlorophyll import CodeView

def retrieve_input():
    inputValue=codeview.get("1.0","end-1c")
    print(inputValue)

root = Tk()
root.title("Window")

codeview = CodeView(root, lexer=pygments.lexers.CLexer, color_scheme="monokai")
codeview.pack(fill="both", expand=True)

buttonCommit=Button(root, height=1, width=10, text="Compile", command=lambda: retrieve_input())
buttonCommit.pack()

root.mainloop()
```

Are you aware of a similar widget as yours that let me embed a coding editor into a Jupyter notebook?

**Comment by Moosems** [comment]
Because these are GUI libs I don't quite know if they will work Jupyter Notebooks, though if I remember properly Jupyter Notebooks are in and of themselves editors and can be opened in VS Code.

**Comment by Nado15** [comment]
Ok I see thanks! I found a slighty different solution, I embedded [CodeMirror](https://codemirror.net/) into my jupyter notebook code. Thanks for help!
