### ISSUE TITLE
Emojis and some weird chars are broken

### ISSUE THREAD

**Issue by rdbende** [rdbende/chlorophyll#5]
@Moosems:

> It works in normal Text pretty well (although with its own issues)but doesn't in chlorophyll

@rdbende:

> Can you provide an example?
In general, Tkinter (Tk) doesn't support most emojis (any character that's beyond U+FFFF, to be precise), so I'm wondering what is what works with the normal text widget but not with Chlorophyll

@Moosems:

> Tkinter recently made them not break widgets so example chars are:

```
😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉 😌
```

> Instructions: Paste and then press backspace

@rdbende:

> https://user-images.githubusercontent.com/77941087/230637196-8cf198af-be1b-4992-994f-eb2a2bcd154e.mp4

@Moosems:

> Very odd... honestly I wish tkinter could support it cause some people use emojis in code and if it doesn't work I'm sure I'm gonna hear about it a lot later on

> @rdbende It happens in mantaray too though so it seems less like a pygments thing

> Happens in Porcupine too, probably due to some Pygments coloring tag that confuses Tk

**Comment by Moosems** [comment]
When this is done on a normal `Text` widget it works fine so there's definitely something going on, I'll have to look into this more and make an MRE.

**Comment by Moosems** [comment]
@rdbende we could check that chard getting tags don't include emojis and if they do include them we can remove the areas with them.

**Comment by Moosems** [comment]
If the char is an emoji don't highlight.
